### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by koczkatamas** [msuhanov/regf#1]
First of all, nice spec docs, great work! :)

Could you add a license to the repo?

If you choose a permissive license, I'd use your work for trying to describe the file format declaratively as part of the @kaitai-io project: https://github.com/kaitai-io/kaitai_struct_formats/blob/master/windows/regf.ksy

**Comment by msuhanov** [comment]
Hello.

I will consider adding a permissive license to this project (currently there is none on purpose).

**Comment by stefv** [comment]
Hi !

Did you decide which licence you will use for this project ? I would like to do a french translation of it, but I want to be sure I can do it. Maybe the Creative Common by-sa is a good choice.

Regards,
Stef

**Comment by msuhanov** [comment]
Done (CC BY 4.0).
