### ISSUE TITLE
How may disable or configure Last reorganized timestamp ?

### ISSUE THREAD

**Issue by Augusto7743** [msuhanov/regf#2]
Hello.
If posting here about ask is wrong excuse me.

In
https://github.com/msuhanov/regf/blob/master/Windows%20registry%20file%20format%20specification.md
In Base Block section
Notes
5. The Last reorganized timestamp field contains a timestamp of the latest hive reorganization (it happens once a week when a hive isn't locked).

How may disable or configure Last reorganized timestampthat setting ?
I wait avoid that feature being used in each week.
Have a mode of lock all registry files when starting Windows thus avoinding that feature ?

Thanks very much.
Have a nice day.

**Comment by msuhanov** [comment]
Hello.

I'm not aware of any way to disable that. It's possible, however, to tweak the interval using the "RegistryReorganizationLimitDays" value (DWORD) in the "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Configuration Manager" key.
